### PR TITLE
Add single-packet mode for servers that violate RCON protocol

### PR DESCRIPTION
**Pull request by wisq**
It seems that many implementations of the RCON protocol don't do multi-packet responses at all, and some exhibit troublesome behaviour — hanging connections, closed connections — if multi-packet requests are made.

I've personally experienced this with Minecraft (although only with certain commands, like `save-all flush`) and I hear it's also an issue with Factorio and some other implementations.  According to the author of a command-line RCON client (https://github.com/n0la/rcon/issues/16#issuecomment-596940603), they decided to make single-packet mode the default for their client going forward, since it's mostly only Valve (Source) servers that supports multi-packet mode anyway.

To get this gem working reliably with my Minecraft server, I added a `single_packet: true` option to `exec/2` (now `exec/3` with a third optional argument), and adjusted `exec_recv/2` so that it returns the first packet immediately if `end_id` is `nil`.  (It might make more sense to have that be a per-connection rather than per-request option, but I elected to keep things simple and not try to extend the connection structure.)

### CODE REVIEW

**Comment by avitex** [comment]
Thank you very much! :heart:

**Comment by avitex** [comment]
Hey @wisq, can you have a look at master now and lemme know if this works well for you?
```
{:rcon, github: "avitex/elixir-rcon"}
```
I don't have a RCON server at hand to test this with.
Cheers!

**Comment by avitex** [comment]
@wisq Gentle poke. Did you have any luck?

**Comment by wisq** [comment]
Hi, sorry, my server was offline for a while and I didn't have a chance to bring it up to test.  I've switched over to the new `multi: false` connect option with the latest master and it seems to work fine.  Thanks!

**Comment by avitex** [comment]
Thanks, I'll publish the changes!

**Pull request merged**
